#include <assert.h>
#include <stdarg.h>
#include "myseqfunctions/kmer.h"
#include "myseqfunctions/kmerIO.h"
#include "myseqfunctions/kmerRead.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <time.h>


void addRawSeq(kmerHolder** khp, int num_args, char** arrp){
  kmerHolder* km = *khp;
  for(int i = 0; i < num_args; i++) {
    char* dtext = arrp[i];
    uint16_t l = strlen(dtext);
    for (int j = 0; j < l; j++){
      updateKmer(&km, &dtext[j], addRelationship);
    }
    resetTrace(&km);
  }
}

#define nseqs 4

int main(int argc, char** argv){
  char* fileout = argv[1];
  if (argc < 2){
    fileout = "/users/vqf/desktop/tmp.txt";
  }
  kmerHolder *km = initKmer(11, 4);
  char* seqs[nseqs] = {
    "AAAAAAAAAAAAATTATTGAATTGAATGGGCTGTTTTTTTATGGAAGAATTGAGGAAAACGTAGGAATCTGACATTTTGAATCAGAAGGTACTGTTTTAACGACTGTTTGGTCACGAGAAAGGCGCGTTTACCGGCGCGAATACCATTCGTCAGGGGCGTTTTGAACAGGCTGATGGCGGTACATTATTTCTCGATGAAATTGGCGATATG",
    "AAAAAAAAAAAAAAATTATTGAATTGAATGGGC",
    "ATCAACATGTTATGTGTTTTATTGAATTGAATGGGCTGTTTTTTTATGGAAGAATTGAGGAAAACGTAGGAATCTGACATTTTGAATCAGAAGGTACTGTTTTAACA",
    "TTTGAACAGGCTGATGGCGGTACATTATTTCTCGATGAAATTGGCGATATTTTTTAAGGAGTTGTTATGATCCACGCCTTTATTAAAAAAGGGTGTTTTCAGGATTCGGTCAGTTTAATGATTATTTCACGAAAACTCAGCGAATCAGAAAATGTTGATGATGTTTCCGTAATGATGGGTACGCCCGCCAATAAAGCGTTATTAGATACCACAGGTTTCTGGCATGACGATTTTAATAACGCCACGCCGAACGATATTTGCGTGGCAATTCGTAGCGAAGCGGAGGATGCGGGGATCGCG",
    //"GTGCGAGATTATGAATCAGAAGGTGCCGGGCGATTTTGCCAAGAAAACGCTGCTGGTTACGACCGGTTCCGAAGCGGTGGAAAACGCGGTGAAAATCGCCCGCGCTGCCACCAAACGTAGCGGCACCATCGCTTTTAGCGGCGCGTATCACGGGCGCACGCATTACACGCTGGCGCTGACCGGCAAGGTGAATCCGTACTCTGCGGGCATGGGCCTGATGCCAGGGCACGTTTATCGCGCGCTTTATCCTT",
    //"CCTGTCGCCAGCTCAATATTAAAACCTGTCAATGTCGGAACTACGAACGTCGTTTCGAGTTTGAACCCGACTGCATTAAATTAACCCGTGAAAATCTGCCAACATTCGAATGGCTACCAATGACCTGCGCTTATCGTTTGCTGGCGGAAGGTAAAGATTTACCTGCGTGGCATCCGCTGCTTACTGGTTCGAAAGCGGCAATGCATGGTGAACGTATCTCTGTGCGTCATATCGCAGTGAACGAATCAGAA",
    //"GCATTAAATTAACCCGTGAAAATCTGCCAACATTCGAATGGCTACCAATGACCTGCGCTTATCGTTTGCTGGCGGAAGGTAAAGATTTACCTGCGTGGCATCCGCTGCTTACTGGTTCGAAAGCGGCAATGCATGGTGAACGTATCTCTGTGCGTCATATCGCAGTGAAAGAATCAGAAGTGATTGACTGGCAGGATCATATCTTAAATAAACCTGACTGGGCGCAGTGATAAATTTAATAGATGTTGATG"
  };
  addRawSeq(&km, nseqs, seqs);
  writeOut(&km, fileout);
  summarize(km->ms);
  //printf("Written\n");
  //kmerHolder* khr = readIn("/users/vqf/desktop/tmp.txt");
  //printf("Read\n");
  //summarize(khr->ms);
  //drawMs(km->ms, "/Users/vqf/Desktop/delme.txt");
  /*uint32_t init = seq2pos(km->ms, "GAAAAAAAAAA");
  kcLL* t = followTrace(&km, init, 1);
  char* yo = getTraceSeq(&km, &t);
  printf("%s\n", yo);
  resetKcLL(&t);
  free(yo);*/
  /*kcLL* ft = nextTrace(&km);
  if (ft){
    char* seq = getTraceSeq(&km, &ft);
    printf("%s\n", seq);
    free(seq);
    resetKcLL(&ft);
  }*/
  destroyKh(&km);
  return 0;
}
